'use client';
import './globals.css';

import Wraper from '@/components/Layout';

import Head from 'next/head';
import { motion as m, useInView, useAnimation } from 'framer-motion';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-[#151515] text-[#fff]">
      <body>
        <Wraper>
          <m.div
            variants={{
              hidden: { opacity: 0, y: 75 },
              vissible: { opacity: 1, y: 0 },
            }}
            initial="hidden"
            animate="vissible"
            transition={{ duration: 2, delay: 0.25 }}
          >
            {children}
          </m.div>
        </Wraper>
      </body>
    </html>
  );
}
